### ISSUE TITLE
'Fellow Humanoids' group is in all capital letters where no other group seems to be. 

### ISSUE THREAD

**Issue by danintexas** [DungeonPatron/DungeonPatronGame#13]
Not sure if intentional or not. 

![image](https://user-images.githubusercontent.com/7607528/105720684-53b9ab80-5ee9-11eb-8fc7-ae46880ef75a.png)

**Comment by MrOnosa** [comment]
AS A FELLOW HUMAN I DO NOT SEE ANYTHING WRONG HERE. ALL OF THE OTHER ~~MODULES~~ TRIBES ARE SHOUTING THEIR NAME. _beep beep_
-Ima Humon

**Comment by Dessyreqt** [comment]
Since @MrOnosa responded in character, I'll just leave this link for the reference we were trying to make instead of doing the same: https://www.reddit.com/r/totallynotrobots/
