### ISSUE TITLE
Speed up!

### ISSUE THREAD

**Issue by FalconMagus** [DungeonPatron/DungeonPatronGame#5]
Could the King Tax happen at 6am and 6 pm to bring more activity in?

Also, could say 1-3 parties enter the dungeon rather than just 1?

I know I'm used to parties going every minute with King tax every hour, but surely a slight pickup won't hurt? I think the event speed is fine. It's a dungeon crawl for a reason.

**Comment by MrOnosa** [comment]
FWIW I have seen two parties in the dungeon at the same time.

**Comment by romulus4444** [comment]
Since we changed the tax to every 6 hours, I'm closing this one.
